[build]
  publish = "dist" # O el directorio donde se encuentre tu index.html y otros assets estáticos si no es la raíz.
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"